  - type: web
    name: hotel-ai-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.hotel_ai.webhook_server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BASEROW_API_TOKEN
        sync: false
